version: 2
updates:
  - package-ecosystem: cargo
    directory: "/compiler-core"
    schedule:
      interval: weekly
      day: tuesday
      time: "09:00"
      timezone: Europe/London
  - package-ecosystem: cargo
    directory: "/compiler-frontend"
    schedule:
      interval: weekly
      day: tuesday
      time: "09:00"
      timezone: Europe/London
  - package-ecosystem: cargo
    directory: "/online-playground"
    schedule:
      interval: weekly
      day: tuesday
      time: "09:00"
      timezone: Europe/London
  - package-ecosystem: npm
    directory: "/online-playground"
    schedule:
      interval: weekly
      day: tuesday
      time: "09:00"
      timezone: Europe/London
