version: 2
updates:
- package-ecosystem: cargo
  directory: "/compiler-core"
  schedule:
    interval: weekly
    day: tuesday
    time: "09:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
- package-ecosystem: cargo
  directory: "/compiler-frontend"
  schedule:
    interval: weekly
    day: tuesday
    time: "09:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: tokio
    versions:
    - 1.1.0
    - 1.1.1
    - 1.2.0
    - 1.3.0
    - 1.4.0
- package-ecosystem: cargo
  directory: "/online-playground"
  schedule:
    interval: weekly
    day: tuesday
    time: "09:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/online-playground"
  schedule:
    interval: weekly
    day: tuesday
    time: "09:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: netlify-cli
    versions:
    - 3.10.2
    - 3.10.6
    - 3.11.0
    - 3.13.6
    - 3.13.8
    - 3.15.0
    - 3.17.1
    - 3.19.0
    - 3.4.2
    - 3.4.6
    - 3.5.0
    - 3.8.1
    - 3.8.5
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: wabt
    versions:
    - 1.0.20
    - 1.0.21
