name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build core
        run: cargo build --verbose
        working-directory: compiler-core

      - name: Test core
        run: cargo test --verbose
        working-directory: compiler-core

      - name: Build compiler frontend
        run: cargo build --verbose
        working-directory: compiler-frontend

      - name: Test compiler frontend
        run: cargo test --verbose
        working-directory: compiler-frontend
