name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --verbose

      - name: Install online playground dependencies
        run: |
          yarn install
          cargo install wasm-pack
        working-directory: online-playground

      - name: Build online playground
        run: yarn build
        working-directory: online-playground

      - name: Deploy online playground
        run: yarn deploy:prod
        working-directory: online-playground
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
