name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Update Rust
        run: rustup update

      - name: Set Cargo home folder
        run: echo "CARGO_HOME=$GITHUB_WORKSPACE/.cargo" >> $GITHUB_ENV

      - name: Add Cargo bin folder to PATH
        run: echo "$CARGO_HOME/bin" >> $GITHUB_PATH

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ${{ env.CARGO_HOME }}/registry/index/
            ${{ env.CARGO_HOME }}/registry/cache/
            ${{ env.CARGO_HOME }}/git/db/
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --verbose --release

      - name: Test
        run: cargo test --verbose --release

      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install online playground dependencies
        run: |
          yarn install
          cargo install wasm-pack
        working-directory: online-playground

      - name: Build online playground
        run: yarn build
        working-directory: online-playground

      - name: Deploy online playground
        run: yarn deploy:prod
        working-directory: online-playground
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
